# -*- coding: utf-8 -*-
"""Thushanth_RAG_Work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbbqEXxxml5A4NBQAOa8BLQ4NyQMXzyF

Creating a working folder in Colab
"""

import os

os.makedirs("ml/llm", exist_ok=True)
print("Folders ready")

"""Adding sample university data"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ml/llm/university_docs.txt
# Students can drop a course within the first two weeks of the semester.
# The deadline for dropping a course is March 15.
# Late submissions will receive penalties unless approved by the lecturer.
#

"""Installing required libraries"""

!pip install langchain chromadb openai tiktoken

"""Setting the OpenAI key"""

import os
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

"""Creating embeddings"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ml/llm/embeddings.py
# from langchain.text_splitter import RecursiveCharacterTextSplitter
# from langchain.embeddings import OpenAIEmbeddings
# from langchain.vectorstores import Chroma
# 
# db = Chroma.from_texts(
#     texts=chunks,
#     embedding=embedding_model,
#     metadatas=[{"source": "University Handbook"}] * len(chunks),
#     persist_directory="ml/llm/chroma_db"
# )
# 
# 
# # 1. Read university text
# with open("ml/llm/university_docs.txt", "r") as file:
#     text = file.read()
# 
# # 2. Split text into smaller chunks
# splitter = RecursiveCharacterTextSplitter(
#     chunk_size=500,
#     chunk_overlap=50
# )
# 
# chunks = splitter.split_text(text)
# 
# # 3. Create embedding model
# embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")
# 
# # 4. Store embeddings in vector database
# db = Chroma.from_texts(
#     texts=chunks,
#     embedding=embedding_model,
#     persist_directory="ml/llm/chroma_db"
# )
# 
# db.persist()
# print("Embeddings created successfully")
#

"""Retrieval logic"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ml/llm/retriever.py
# from langchain.embeddings import OpenAIEmbeddings
# from langchain.vectorstores import Chroma
# 
# embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")
# 
# db = Chroma(
#     persist_directory="ml/llm/chroma_db",
#     embedding_function=embedding_model
# )
# 
# def retrieve_context(question, k=3):
#     results = db.similarity_search(question, k=k)
#     return [doc.page_content for doc in results]
#

"""Prompt rules"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ml/llm/prompt.py
# SYSTEM_PROMPT = """
# You are a university academic assistant.
# Answer ONLY using the given context.
# If the answer is not in the context, say you do not know.
# """
#

"""Full test"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ml/llm/test_query.py
# from openai import OpenAI
# from retriever import retrieve_context
# from prompt import SYSTEM_PROMPT
# 
# client = OpenAI()
# 
# question = "What is the deadline for dropping a course?"
# 
# context = retrieve_context(question)
# 
# 
# context_text = "\n".join(context)
# 
# response = client.chat.completions.create(
#     model="gpt-4o-mini",
#     messages=[
#         {"role": "system", "content": SYSTEM_PROMPT},
#         {"role": "user", "content": f"Context:\n{context_text}\n\nQuestion:\n{question}"}
#     ]
# )
# 
# if not context:
#     print("No relevant context found.")
# 
# 
# print("Question:", question)
# print("Answer:", response.choices[0].message.content)
#